LoginPy/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
]

applications/home/urls.py
from django.urls import path

from . import views

app_name = 'home_app'

urlpatterns = [
    path('panel/', views.HomePage.as_view(), name='panel'),
    path('mixin/', views.TemplatePruebaMixin.as_view(), name='mixin'),
]

applications/users/urls.py
from django.urls import path

from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.LoginUser.as_view(), name='user-login'),
    path('logout/', views.LogoutView.as_view(), name='user-logout'),
    path('update/', views.UpdatePasswordView.as_view(), name='password-update'),
    path('user_verification/<pk>/', views.CodeVerificationView.as_view(), name='user_verification'),
]

applications/home/models.py
from django.db import models

# Create your models here.

applications/home/views.py
from django.shortcuts import render
import datetime

# Create your views here.

from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse


class HomePage(LoginRequiredMixin, TemplateView):
    template_name = "home/index.html"
    login_url = reverse_lazy('users_app:user-login')


class FechaMixin(object):
    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha'] = datetime.datetime.now()
        return context


class TemplatePruebaMixin(FechaMixin, TemplateView):
    template_name = "home/mixin.html"

templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>

<h1>Panel de Usuario</h1>
<h3> Bienvenido: {{ user }}</h3>


<ul>
    <li><a href="{% url 'users_app:user-logout' %}">Cerrar Sesion</a> </li>
    <li><a href="{% url 'users_app:password-update' %}">Actualizar Datos</a> </li>
    
</ul>
</body>
</html>

templates/home/mixin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ fecha }}</title>
</head>
<body>

</body>
</html>